# https://github.com/oneapi-src/oneapi-ci/blob/master/.github/workflows/build_all.yml

name: CI

on: push

env:
  LINUX_BASEKIT_SH: l_BaseKit_p_2022.2.0.262_offline.sh
  LINUX_HPCKIT_SH: l_HPCKit_p_2022.2.0.191_offline.sh
  LINUX_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18673/l_BaseKit_p_2022.2.0.262_offline.sh
  LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18679/l_HPCKit_p_2022.2.0.191_offline.sh
  LINUX_FORTRAN_COMPONENTS_WEB: intel.oneapi.lin.ifort-compiler
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache install
        id: cache-install
        uses: actions/cache@v2
        with:
          path: |
            /opt/intel/oneapi/compiler
          key: install-${{ env.LINUX_HPCKIT_URL }}-${{ env.LINUX_FORTRAN_COMPONENTS_WEB }}-compiler
      - name: install fortran
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install intel-oneapi-openmp intel-oneapi-mpi  intel-oneapi-mpi-devel intel-oneapi-mkl intel-oneapi-compiler-fortran intel-oneapi-common-licensing
          echo -e "\nsource /opt/intel/oneapi/setvars.sh > /dev/null" >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install pytest for unit test
        run: python -m pip install pytest
      - name: Build source code
        run: |
          mkdir build
          cd build
          FC=ifort cmake ..
          make &&
      - name: Run unittest
        run: |
          cd test
          pytest test1.py
